name = "Modules Enhanced";
action = "https://github.com/hypoxia125/Modules-Enhanced";
actionName = "Github";
author = "Hypoxic";
hideName = 0;
hidePicture = 0;
logo = "\z\meh\addons\main\data\logoModulesEnhanced_ca.paa";
logoOver = "\z\meh\addons\main\data\logoModulesEnhanced_ca.paa";
logoSmall = "\z\meh\addons\main\data\logoModulesEnhanced_ca.paa";
overview = "Adds new useful 3DEN modules for mission makers and fixes outdated BI modules.<br/><a href='https://www.bohemia.net/community/licenses/arma-public-license-share-alike'><t underline='true'>This content is under APL-SA license.</t><br/></a><br/><t size='1.5'><img image='\z\meh\addons\main\data\APL-SA_Custom_ca.paa' /></t><br/><br/><t size='1.1' color='#11115'>Re-uploading to the Steam Workshop is prohibited!</t>";
picture = "\z\meh\addons\main\data\imgModulesEnhanced_ca.paa";
tooltipOwned = "Adds new useful 3DEN modules for mission makers and fixes outdated BI modules.";
