#define GUI_GRID_X	(0.5)
#define GUI_GRID_Y	(0.5)
#define GUI_GRID_W	(((safezoneW / safezoneH) min 1.2) / 40)
#define GUI_GRID_H	((((safezoneW / safezoneH) min 1.2) / 1.2) / 25)
#define GUI_GRID_WAbs	(0)
#define GUI_GRID_HAbs	(0)
