// AmbientArtilleryVirtual
#define AMBIENTARTILLERYVIRTUAL_SHELL                    'SH_82mm_AMOS'
#define AMBIENTARTILLERYVIRTUAL_TIMELENGTH               60
#define AMBIENTARTILLERYVIRTUAL_SALVOSIZE                6
#define AMBIENTARTILLERYVIRTUAL_SALVOINTERVAL            10
#define AMBIENTARTILLERYVIRTUAL_SALVOTIMERVARIATION      5
#define AMBIENTARTILLERYVIRTUAL_SHOTINTERVAL             1
#define AMBIENTARTILLERYVIRTUAL_SHOTTIMEVARIATION        1
