PREP(moduleAmbientArtilleryVirtual);
PREP(moduleCommunicationJammer);
PREP(moduleCreateMinefield);
PREP(moduleDeleteRespawnPosition);
PREP(moduleEffectFire);
PREP(moduleEffectLightpoint);
PREP(moduleEffectSmoke);
PREP(moduleEnableDisableGunLights);
PREP(moduleLightningStorm);
PREP(moduleMoveOnCombat);
PREP(moduleMPSync);
PREP(moduleParadropVehicle);
PREP(moduleRegisterTeleporter);
PREP(moduleSpeedLimiter);
PREP(moduleTrapInventory);
PREP(moduleVehicleMineJammer);
PREP(moduleVehicleRearm);
PREP(moduleVehicleRefuel);

PREP(ambientArtilleryVirtual);
PREP(createMinefield);
PREP(deleteRespawnPosition);
PREP(enableDisableGunLights);
PREP(lightningStorm);
PREP(get3DENAreaModule);
PREP(moveOnCombat);
PREP(paradropVehicle);
PREP(speedLimiter);
PREP(trapInventory);
PREP(trapInventoryActionShow);
PREP(vehicleMineJammer);
PREP(vehicleRearm);
PREP(vehicleRefuel);

INFO("PREP: Functions loaded successfully");
