PREP(moduleAmbientArtilleryVirtual);
PREP(moduleAntiTroll);
PREP(moduleCommunicationJammer);
PREP(moduleCreateMinefield);
PREP(moduleDeleteRespawnPosition);
PREP(moduleEffectFire);
PREP(moduleEffectFlareLauncher);
PREP(moduleEffectLightpoint);
PREP(moduleEffectSmoke);
PREP(moduleEnableDisableGunLights);
PREP(moduleHealingArea);
PREP(moduleLightningStorm);
PREP(moduleMoveOnCombat);
PREP(moduleParadropTroopTransport);
PREP(moduleMPSync);
PREP(moduleParadropVehicle);
PREP(moduleRegisterTeleporter);
PREP(moduleSpeedLimiter);
PREP(moduleTrapInventory);
PREP(moduleVehicleMineJammer);
PREP(moduleVehicleRearm);
PREP(moduleVehicleRefuel);

PREP(healingArea);
PREP(get3DENAreaModule);
PREP(paradropTroopTransport);
PREP(paradropVehicle);
PREP(speedLimiter);
PREP(trapInventory);
PREP(trapInventoryActionShow);
PREP(vehicleMineJammer);
PREP(vehicleRearm);
PREP(vehicleRefuel);

INFO("PREP: Functions loaded successfully");
