PREP(moduleAmbientArtilleryVirtual);
PREP(moduleAntiTroll);
PREP(moduleChangeFlag);
PREP(moduleClearMapLocationNames);
PREP(moduleCommunicationJammer);
PREP(moduleCreateMinefield);
PREP(moduleCreateMapLocation);
PREP(moduleCreateRemoteTarget);
PREP(moduleDeleteRespawnPosition);
PREP(moduleEffectFire);
PREP(moduleEffectFlareLauncher);
PREP(moduleEffectLightpoint);
PREP(moduleEffectSmoke);
PREP(moduleEnableDisableGunLights);
PREP(moduleHealingArea);
PREP(moduleInfantrySpawner);
PREP(moduleLightningStorm);
PREP(moduleMoveOnCombat);
PREP(moduleParadropTroopTransport);
PREP(moduleMPSync);
PREP(moduleParadropVehicle);
PREP(moduleRegisterTeleporter);
PREP(moduleSpawnerWaypoint);
PREP(moduleSpeedLimiter);
PREP(moduleTrapInventory);
PREP(moduleVehicleFuelCoef);
PREP(moduleVehicleMineJammer);
PREP(moduleVehicleRearm);
PREP(moduleVehicleRefuel);
PREP(moduleVehicleRepair);

PREP(get3DENAreaModule);

INFO("PREP: Functions loaded successfully");
